// <auto-generated />
namespace PassionProjectFlowerShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class occasion3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(occasion3));
        
        string IMigrationMetadata.Id
        {
            get { return "202308190155428_occasion3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
