// <auto-generated />
namespace PassionProjectFlowerShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class flowerbouquetoccasion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(flowerbouquetoccasion));
        
        string IMigrationMetadata.Id
        {
            get { return "202307310328329_flower-bouquet-occasion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
